categories:
- ChIP-seq
description: An automated pipeline for processing DamID sequencing datasets
long_description: |
    Processing DamID-seq data involves extending single-end reads, aligning the
    reads to the genome and determining the coverage, similar to processing
    regular ChIP-seq datasets. However, as DamID data is represented as a log2
    ratio of (Dam-fusion/Dam), normalisation of the sample and Dam-only control
    is necessary and adding pseudocounts to mitigate the effect of background
    counts is highly recommended.

    damidseq_pipeline is a single script that automatically handles sequence
    alignment, read extension, binned counts, normalisation, pseudocount
    addition and final ratio file generation. The script uses FASTQ or BAM
    files as input, and outputs the final log2 ratio files in bedGraph (or
    optionally GFF) format.

    The output ratio files can easily be converted to TDF for viewing in IGV
    using igvtools. The files can be processed for peak calling using
    find_peaks or, if using RNA pol II DamID, transcribed genes can be
    determined using polii.gene.call.
name: damidseq_core
owner: mvdbeek
remote_repository_url:
    https://github.com/galaxyproject/tools-iuc/tree/master/tools/damidseq_core
type:
    unrestricted
