categories:
- Text Manipulation
- Convert Formats
- ChIP-seq
description: bwtool is a command-line utility for bigWig files
long_description: |
  bwtool is a command-line utility for bigWig files. bigWigs are an
  indexed and compressed form of wig file, a somewhat standard format
  for storing genome-wide real-valued signal data. Much of the ENCODE
  processed data is in this form, and it is appearing more often in GEO as well.
  The purpose of bwtool is to make these files more useful by providing some convenient functions.

  https://github.com/CRG-Barcelona/bwtool/wiki
name: bwtool
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/bwtool
type: unrestricted
